window.ARTICLE_LIBRARY = {
  en: [
    {
      id:'hr-diagnosis', category:'HR & Problem Solving', title:'Why HR Problems Are Often Diagnosed the Wrong Way',
      excerpt:'A practical framework for moving from symptoms and assumptions to evidence, root causes, intervention and follow-up.',
      cover:'cover-diagnosis',
      read:'8 min',
      content:`<p>Many HR interventions fail before implementation begins because the organization starts by naming a solution instead of defining the problem. A request for training may actually be a management problem. A request to replace an employee may hide unclear expectations. A request for more hiring may be caused by weak retention or poor workforce planning.</p><h2>Start with the problem, not the solution</h2><p>Use five questions before selecting an intervention: What is happening? Who is affected? When did it start? What evidence confirms it? What business or people outcome is being damaged?</p><h2>A practical diagnostic sequence</h2><ol><li><strong>Describe the observable symptom.</strong> Avoid labels such as “low motivation” until behavior and evidence are clear.</li><li><strong>Separate facts from interpretations.</strong> Interview managers and employees separately and compare what each group observes.</li><li><strong>Test four cause families:</strong> expectations, capability, context/resources, and management/process.</li><li><strong>Select the smallest useful intervention.</strong> Fix clarity before training; fix process before blaming people.</li><li><strong>Set a follow-up point.</strong> Agree what evidence would show improvement and when it will be reviewed.</li></ol><h2>Where AI can strengthen the work</h2><p>AI can organize interview notes, cluster recurring themes, compare statements, draft diagnostic questions and surface patterns that deserve human review. It should not decide who is at fault or make a sensitive employment decision without human judgment, evidence and appropriate controls.</p><h2>Implementation template</h2><p><strong>Problem statement → evidence → hypotheses → verification questions → intervention → owner → follow-up evidence.</strong> This turns HR from a service desk into a decision partner.</p>`
    },
    {
      id:'evidence-hiring', category:'Talent Acquisition', title:'From CV Screening to Evidence-Based Hiring',
      excerpt:'How recruiters can move beyond keywords and impressions toward structured, job-related evidence.',
      cover:'cover-hiring', read:'9 min',
      content:`<p>Hiring quality improves when the organization can explain why a candidate is suitable using evidence that is relevant to the work. A polished CV or confident interview should be a signal, not the decision itself.</p><h2>Build the selection logic before meeting candidates</h2><p>Translate the job into a short set of outcomes and competencies. For each one, define what acceptable evidence looks like. This prevents interviews from becoming conversations driven by personality and first impressions.</p><h2>A stronger selection flow</h2><ol><li>Clarify the outcomes expected in the first 6–12 months.</li><li>Identify the few competencies that actually drive those outcomes.</li><li>Use structured questions and consistent scoring criteria.</li><li>Add work samples or realistic scenarios for critical skills.</li><li>Document evidence separately from personal impressions.</li><li>Use reference checks to verify material claims where appropriate.</li></ol><h2>Where AI adds value</h2><p>AI can compare a CV with a job description, identify missing evidence, suggest structured interview questions, summarize candidate information and generate follow-up questions. It should not silently reject people or become an unvalidated proxy for “culture fit”. Human review, job relevance, fairness checks and clear governance remain essential.</p><h2>Implementation</h2><p>Create a simple evidence matrix: <strong>requirement → evidence found → evidence missing → verification method → final human judgment.</strong> This is more defensible than a mysterious candidate score.</p>`
    },
    {
      id:'performance-root-cause', category:'Performance', title:'When Performance Falls: Find the Real Cause Before You Intervene',
      excerpt:'A manager-friendly method for separating capability gaps from unclear expectations, system barriers and leadership issues.',
      cover:'cover-performance', read:'8 min',
      content:`<p>A drop in performance is an outcome, not a diagnosis. Treating every performance problem as a training issue wastes time and can make the situation worse.</p><h2>The four-question test</h2><p>Ask: Does the person know what good performance looks like? Can they perform it? Do they have the resources and process to do it? Are leadership and accountability reinforcing the expected behavior?</p><h2>Interventions by cause</h2><ul><li><strong>Clarity problem:</strong> reset outcomes, priorities, standards and decision rights.</li><li><strong>Capability problem:</strong> provide practice, coaching, job aids and feedback.</li><li><strong>Context problem:</strong> remove bottlenecks, conflicting priorities or missing resources.</li><li><strong>Management problem:</strong> address inconsistent feedback, poor delegation or weak follow-through.</li></ul><h2>AI and performance management</h2><p>AI can summarize feedback, identify recurring themes and help managers prepare for difficult conversations. It should not be used as an opaque scoring engine for employees. Performance decisions require context, evidence and accountable human review.</p><h2>Execution checklist</h2><p>Document the gap, confirm the cause, agree on the next behavior, provide support, set a review date and record what changed. If the intervention fails, return to diagnosis instead of escalating automatically.</p>`
    },
    {
      id:'career-shift-hr', category:'Career Development', title:'How to Make a Career Shift into HR Without Starting From Zero',
      excerpt:'A practical transition model for turning previous experience into credible HR evidence and a coherent career story.',
      cover:'cover-career', read:'10 min',
      content:`<p>A career shift into HR does not require deleting your previous career. The strongest transitions identify transferable evidence, build missing HR capability and create proof that the target role can be performed.</p><h2>Step 1: Choose a specific HR destination</h2><p>“I want to work in HR” is too broad. Compare your current experience with roles such as talent acquisition, learning, employee relations, HR operations, people analytics or HR business partnering.</p><h2>Step 2: Map transferable evidence</h2><p>Look for experiences involving stakeholder management, interviewing, coaching, conflict resolution, data, project delivery, policy, customer experience or change. Translate them into the language of the target work without exaggeration.</p><h2>Step 3: Build the missing capability</h2><p>Prioritize only the gaps that matter for your chosen role. Learn, practice and create work evidence through projects, volunteering, simulations or internal assignments.</p><h2>Step 4: Build a credible story</h2><p>Your career narrative should connect <strong>where you came from → what you learned → why HR → what you can already contribute → what you deliberately built for the new role.</strong></p><h2>AI as a career accelerator</h2><p>AI can help analyze job descriptions, identify transferable skills, generate practice scenarios, critique interview answers and turn experience into evidence-based CV language. It should support your reasoning rather than invent experience.</p>`
    },
    {
      id:'ai-employee-lifecycle', category:'AI & Future of Work', title:'AI Across the Employee Lifecycle: Where to Automate, Where to Augment and Where Humans Must Decide',
      excerpt:'A practical governance model for using AI across recruitment, onboarding, learning, performance and employee experience.',
      cover:'cover-ai', read:'11 min',
      content:`<p>The useful question is not “Where can we put AI?” but “Which parts of the work benefit from AI, and what must remain accountable to people?”</p><h2>Three levels of use</h2><ol><li><strong>Automate:</strong> repetitive, rules-based work with clear controls and low consequence.</li><li><strong>Augment:</strong> analysis, drafting, summarization and preparation where a person reviews the output.</li><li><strong>Human decision:</strong> consequential employment judgments where context, fairness, accountability and escalation matter.</li></ol><h2>Across the lifecycle</h2><p>In recruiting, AI can help structure job requirements and prepare interview questions. In onboarding, it can personalize guidance. In learning, it can recommend practice. In performance, it can organize feedback themes. In employee experience, it can surface recurring questions. The level of human oversight should rise with the consequence of the decision.</p><h2>Implementation architecture</h2><p>Define the use case, data source, intended user, decision boundary, validation method, human reviewer, escalation path and monitoring process before deployment.</p><h2>The strategic shift</h2><p>The future HR professional will need to understand people, process, data and AI together. The competitive advantage will not come from using the most AI tools; it will come from redesigning work responsibly around better decisions.</p>`
    },
    {
      id:'skills-based-hr', category:'Future of Work', title:'From Jobs to Skills: How HR Can Prepare for a More Fluid Workforce',
      excerpt:'Why organizations are moving toward skills-based thinking and how HR can turn the idea into workforce decisions.',
      cover:'cover-skills', read:'10 min',
      content:`<p>Job titles are useful labels, but they are increasingly poor descriptions of how work actually changes. A skills-based approach asks what people can do, what the organization will need next and how capability can move across roles.</p><h2>What changes for HR?</h2><p>Workforce planning becomes a capability conversation. Talent acquisition focuses more on evidence of skills. Learning becomes closer to business demand. Internal mobility becomes a strategic lever rather than an informal process.</p><h2>Implementation path</h2><ol><li>Identify strategic capabilities linked to business priorities.</li><li>Break critical roles into observable skills and behaviors.</li><li>Map current capability using evidence, not self-labels alone.</li><li>Identify build, buy, borrow and redeploy options.</li><li>Create internal pathways that connect skills to opportunities.</li><li>Review the capability map regularly as work changes.</li></ol><h2>AI's role</h2><p>AI can help normalize job descriptions, cluster skills, detect emerging requirements and recommend learning or mobility options. The organization still needs human governance to validate definitions, protect employee interests and prevent algorithmic shortcuts.</p><h2>The practical outcome</h2><p>A skills-based model is valuable only when it changes a real decision: who to hire, who to develop, where to redeploy people, which capabilities to build and what work should be redesigned.</p>`
    }
  ],
  ar: [
    {id:'hr-diagnosis',category:'الموارد البشرية وحل المشكلات',title:'لماذا يتم تشخيص مشكلات الموارد البشرية بطريقة خاطئة؟',excerpt:'من الأعراض والانطباعات إلى الأدلة والسبب الحقيقي والتدخل والمتابعة.',cover:'cover-diagnosis',read:'٨ دقائق',content:`<p>كثير من تدخلات الموارد البشرية تفشل قبل أن تبدأ لأن المنظمة تسمي الحل قبل أن تحدد المشكلة. قد يكون طلب التدريب في حقيقته مشكلة في الإدارة، وقد يخفي طلب استبدال موظف غموضًا في التوقعات، وقد يكون طلب التوظيف الجديد نتيجة لضعف الاحتفاظ بالموظفين.</p><h2>ابدأ بالمشكلة لا بالحل</h2><p>قبل اختيار أي تدخل، اسأل: ماذا يحدث؟ من المتأثر؟ متى بدأت المشكلة؟ ما الأدلة؟ وما الأثر على العمل أو الأفراد؟</p><h2>منهج عملي للتشخيص</h2><ol><li><strong>صف السلوك أو النتيجة الملاحظة.</strong> لا تستخدم وصفًا مثل «ضعف الدافعية» قبل تحديد السلوك والأدلة.</li><li><strong>افصل الحقائق عن التفسيرات.</strong> تحدث مع المدير والموظف وقارن ما يراه كل طرف.</li><li><strong>اختبر أربع مجموعات من الأسباب:</strong> التوقعات، والقدرة، والموارد والسياق، والإدارة والعملية.</li><li><strong>اختر أصغر تدخل مفيد.</strong> عالج الوضوح قبل التدريب، والعملية قبل لوم الأفراد.</li><li><strong>حدد موعدًا للمتابعة.</strong> اتفق على الدليل الذي سيظهر التحسن وموعد مراجعته.</li></ol><h2>أين يساعد الذكاء الاصطناعي؟</h2><p>يمكنه تنظيم ملاحظات المقابلات، وتجميع الموضوعات المتكررة، ومقارنة الإفادات، واقتراح أسئلة تشخيصية. لكنه لا ينبغي أن يقرر من المخطئ أو يتخذ قرارًا وظيفيًا حساسًا دون مراجعة بشرية وأدلة وضوابط مناسبة.</p><h2>قالب التنفيذ</h2><p><strong>صياغة المشكلة ← الأدلة ← الفرضيات ← أسئلة التحقق ← التدخل ← المسؤول ← دليل المتابعة.</strong></p>`},
    {id:'evidence-hiring',category:'استقطاب المواهب',title:'من فرز السير الذاتية إلى التوظيف القائم على الأدلة',excerpt:'كيف ينتقل المستقطب من الكلمات والانطباعات إلى أدلة مرتبطة بالوظيفة.',cover:'cover-hiring',read:'٩ دقائق',content:`<p>تتحسن جودة التوظيف عندما تستطيع المنظمة تفسير سبب ملاءمة المرشح من خلال أدلة مرتبطة بالعمل. السيرة القوية أو الثقة في المقابلة إشارات مهمة، لكنها لا ينبغي أن تكون القرار وحدها.</p><h2>ابنِ منطق الاختيار قبل مقابلة المرشحين</h2><p>حوّل الوظيفة إلى نتائج متوقعة وكفاءات أساسية، ثم حدد شكل الدليل المقبول لكل منها.</p><h2>مسار اختيار أقوى</h2><ol><li>حدد النتائج المتوقعة خلال الأشهر الأولى.</li><li>حدد الكفاءات التي تؤثر فعليًا في هذه النتائج.</li><li>استخدم أسئلة منظمة ومعايير موحدة.</li><li>أضف عينات عمل أو مواقف واقعية للمهارات الحرجة.</li><li>وثق الأدلة منفصلة عن الانطباعات الشخصية.</li><li>تحقق من الادعاءات المهمة عندما يكون ذلك مناسبًا.</li></ol><h2>دور الذكاء الاصطناعي</h2><p>يمكنه مقارنة السيرة بالوصف الوظيفي، وتحديد الأدلة الناقصة، واقتراح أسئلة مقابلة منظمة، وتلخيص المعلومات. لكنه لا ينبغي أن يرفض المتقدمين بصورة خفية أو يحول «الملاءمة الثقافية» إلى حكم غير منضبط.</p><h2>التنفيذ</h2><p>أنشئ مصفوفة: <strong>المتطلب ← الدليل الموجود ← الدليل الناقص ← طريقة التحقق ← الحكم البشري النهائي.</strong></p>`},
    {id:'performance-root-cause',category:'الأداء',title:'عندما ينخفض الأداء: اكتشف السبب الحقيقي قبل أن تتدخل',excerpt:'طريقة عملية للتمييز بين فجوة القدرة وغموض التوقعات وعوائق النظام ومشكلات الإدارة.',cover:'cover-performance',read:'٨ دقائق',content:`<p>انخفاض الأداء نتيجة وليس تشخيصًا. اعتبار كل مشكلة أداء مشكلة تدريب يهدر الوقت وقد يزيد المشكلة.</p><h2>اختبار الأسئلة الأربعة</h2><p>هل يعرف الموظف شكل الأداء المطلوب؟ هل يستطيع تنفيذه؟ هل لديه الموارد والعملية اللازمة؟ وهل الإدارة والمساءلة تعززان السلوك المطلوب؟</p><h2>التدخل بحسب السبب</h2><ul><li><strong>مشكلة وضوح:</strong> إعادة ضبط النتائج والأولويات والمعايير وصلاحيات القرار.</li><li><strong>مشكلة قدرة:</strong> تدريب عملي وتوجيه وممارسة وتغذية راجعة.</li><li><strong>مشكلة سياق:</strong> إزالة الاختناقات وتعارض الأولويات ونقص الموارد.</li><li><strong>مشكلة إدارة:</strong> معالجة ضعف المتابعة أو التفويض أو التغذية الراجعة.</li></ul><h2>الذكاء الاصطناعي وإدارة الأداء</h2><p>يمكنه تلخيص الملاحظات واكتشاف الموضوعات المتكررة ومساعدة المدير في التحضير للمحادثات الصعبة، لكنه لا ينبغي أن يتحول إلى آلة تقييم غامضة للموظفين.</p><h2>قائمة التنفيذ</h2><p>وثق الفجوة، تحقق من السبب، اتفق على السلوك التالي، قدم الدعم، حدد موعد المراجعة، وسجل ما تغير. وإذا لم ينجح التدخل، عد إلى التشخيص بدل التصعيد التلقائي.</p>`},
    {id:'career-shift-hr',category:'التطوير المهني',title:'كيف تقوم بعمل تحول مهني إلى الموارد البشرية دون أن تبدأ من الصفر؟',excerpt:'منهج عملي لتحويل خبرتك السابقة إلى أدلة مهنية وبناء قصة انتقال مقنعة.',cover:'cover-career',read:'١٠ دقائق',content:`<p>التحول إلى الموارد البشرية لا يعني حذف خبرتك السابقة. أقوى الانتقالات تحدد الخبرات القابلة للنقل، وتبني القدرات الناقصة، وتصنع دليلًا على القدرة على أداء الدور المستهدف.</p><h2>الخطوة الأولى: حدد الوجهة</h2><p>عبارة «أريد العمل في الموارد البشرية» واسعة جدًا. حدد مسارًا مثل استقطاب المواهب أو التعلم أو علاقات الموظفين أو عمليات الموارد البشرية أو تحليلات الأفراد أو شراكة الأعمال.</p><h2>الخطوة الثانية: خريطة الأدلة القابلة للنقل</h2><p>ابحث عن خبرات في إدارة أصحاب المصلحة، والمقابلات، والتوجيه، وحل الصراعات، والبيانات، وإدارة المشروعات، والسياسات، وتجربة العميل أو التغيير.</p><h2>الخطوة الثالثة: ابنِ القدرات الناقصة</h2><p>ركز على الفجوات المهمة للدور المستهدف فقط، ثم تعلم ومارس وابنِ أدلة من مشروعات أو مهام داخلية أو تجارب تطبيقية.</p><h2>الخطوة الرابعة: ابنِ قصة مهنية متماسكة</h2><p><strong>من أين بدأت ← ماذا تعلمت ← لماذا الموارد البشرية ← ما القيمة التي أقدمها الآن ← ماذا بنيت استعدادًا للدور الجديد.</strong></p><h2>الذكاء الاصطناعي كمسرّع مهني</h2><p>يمكن استخدامه لتحليل أوصاف الوظائف، وتحديد المهارات القابلة للنقل، وبناء مواقف تدريبية، ومراجعة إجابات المقابلات، وتحويل الخبرة إلى صياغة قائمة على الأدلة دون اختلاق خبرات.</p>`},
    {id:'ai-employee-lifecycle',category:'الذكاء الاصطناعي ومستقبل العمل',title:'الذكاء الاصطناعي عبر دورة حياة الموظف: أين نؤتمت وأين نعزز وأين يبقى القرار بشريًا؟',excerpt:'نموذج عملي لاستخدام الذكاء الاصطناعي في التوظيف والتعيين والتعلم والأداء وتجربة الموظف.',cover:'cover-ai',read:'١١ دقيقة',content:`<p>السؤال المفيد ليس «أين نضع الذكاء الاصطناعي؟» بل «أي أجزاء العمل تستفيد منه، وما الذي يجب أن يبقى تحت مسؤولية الإنسان؟»</p><h2>ثلاثة مستويات للاستخدام</h2><ol><li><strong>الأتمتة:</strong> الأعمال المتكررة والقائمة على قواعد واضحة مع ضوابط مناسبة.</li><li><strong>التعزيز:</strong> التحليل والصياغة والتلخيص والتحضير مع مراجعة بشرية.</li><li><strong>القرار البشري:</strong> القرارات الوظيفية ذات الأثر الكبير حيث السياق والعدالة والمساءلة والتصعيد مهمة.</li></ol><h2>عبر دورة حياة الموظف</h2><p>في الاستقطاب يمكنه تنظيم متطلبات الوظيفة وإعداد أسئلة المقابلة. وفي التهيئة يمكنه تخصيص الإرشاد. وفي التعلم يمكنه اقتراح التدريب. وفي الأداء يمكنه تنظيم موضوعات الملاحظات. وكلما زاد أثر القرار، يجب أن ترتفع درجة الإشراف البشري.</p><h2>بنية التنفيذ</h2><p>حدد حالة الاستخدام، ومصدر البيانات، والمستخدم، وحدود القرار، وطريقة التحقق، والمسؤول البشري، ومسار التصعيد، وآلية المتابعة قبل التشغيل.</p><h2>التحول الاستراتيجي</h2><p>محترف الموارد البشرية المستقبلي سيحتاج إلى فهم الأفراد والعمليات والبيانات والذكاء الاصطناعي معًا. الميزة التنافسية ليست في استخدام أكبر عدد من الأدوات، بل في إعادة تصميم العمل حول قرارات أفضل.</p>`},
    {id:'skills-based-hr',category:'مستقبل العمل',title:'من الوظائف إلى المهارات: كيف تستعد الموارد البشرية لقوة عمل أكثر مرونة؟',excerpt:'لماذا تتجه المؤسسات إلى التفكير القائم على المهارات وكيف يتحول ذلك إلى قرارات عملية.',cover:'cover-skills',read:'١٠ دقائق',content:`<p>المسميات الوظيفية مفيدة، لكنها لا تصف دائمًا كيف يتغير العمل. التفكير القائم على المهارات يسأل: ماذا يستطيع الناس أن يفعلوا؟ وما القدرات التي ستحتاجها المؤسسة لاحقًا؟ وكيف تنتقل المهارات بين الأدوار؟</p><h2>ما الذي يتغير في الموارد البشرية؟</h2><p>يصبح تخطيط القوى العاملة حوارًا حول القدرات، ويركز الاستقطاب أكثر على الأدلة، ويقترب التعلم من احتياجات العمل، وتصبح الحركة الداخلية أداة استراتيجية.</p><h2>مسار التنفيذ</h2><ol><li>حدد القدرات الاستراتيجية المرتبطة بأولويات العمل.</li><li>فكك الأدوار الحرجة إلى مهارات وسلوكيات قابلة للملاحظة.</li><li>ارسم صورة للقدرات الحالية اعتمادًا على الأدلة.</li><li>حدد ما الذي يجب بناؤه أو استقطابه أو إعادة توزيعه.</li><li>أنشئ مسارات داخلية تربط المهارات بالفرص.</li><li>راجع خريطة القدرات دوريًا مع تغير العمل.</li></ol><h2>دور الذكاء الاصطناعي</h2><p>يمكنه توحيد أوصاف الوظائف، وتجميع المهارات، واكتشاف المتطلبات الناشئة، واقتراح مسارات تعلم أو حركة داخلية. لكن الحوكمة البشرية تظل ضرورية.</p><h2>النتيجة العملية</h2><p>لا قيمة لنموذج قائم على المهارات إذا لم يغير قرارًا حقيقيًا: من نوظف، ومن نطور، ومن نعيد توزيعه، وما القدرات التي نبنيها، وما العمل الذي نعيد تصميمه.</p>`}
  ]
};
